<?php

namespace Tests\Unit\Services\Finance;

use App\Models\User;
use App\Services\Finance\UpdateUserBalance;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class UpdateUserBalanceTest extends TestCase
{
    use RefreshDatabase;
    protected UpdateUserBalance $updateUserBalance;
    protected Model $user;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->updateUserBalance = app()->make(UpdateUserBalance::class);
        $this->user = User::factory()->create([
            'cash' => 200.00
        ]);
    }

    /**
     * A basic unit test example.
     */
    public function test_user_balance_positive_update(): void
    {
        $this->updateUserBalance->execute($this->user->id, 200.00);
        $this->user->refresh();
        $this->assertEquals(400.00, $this->user->cash);
    }

    public function test_user_balance_negative_update(): void
    {
        $this->updateUserBalance->execute($this->user->id, -100.00);
        $this->user->refresh();
        $this->assertEquals(100.00, $this->user->cash);
    }
}
