<?php

namespace Tests\Unit\Models;

use App\Models\Aircraft;
use App\Models\AircraftEngine;
use App\Models\AircraftManufacturer;
use App\Models\AircraftType;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class AircraftTest extends TestCase
{
    use RefreshDatabase;
    protected Model $acType;
    protected Model $manufacturer;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->manufacturer = AircraftManufacturer::factory()->create();
        $this->acType = AircraftType::factory()->create([
            'aircraft_manufacturer_id' => $this->manufacturer->id
        ]);
    }

    /**
     * A basic unit test example.
     */
    public function test_aircraft_condition_returns_100(): void
    {
        $aircraft = Aircraft::factory()->create();
        AircraftEngine::factory()->create([
            'aircraft_id' => $aircraft->id
        ]);
        $this->assertEquals(100, $aircraft->total_condition);
    }

    public function test_aircraft_condition_returns_75(): void
    {
        $aircraft = Aircraft::factory()->create([
            'condition' => 50
        ]);
        AircraftEngine::factory()->create([
            'aircraft_id' => $aircraft->id
        ]);
        $this->assertEquals(75, $aircraft->total_condition);
    }

    public function test_aircraft_condition_returns_50(): void
    {
        $aircraft = Aircraft::factory()->create([
            'condition' => 50
        ]);
        AircraftEngine::factory()->create([
            'aircraft_id' => $aircraft->id,
            'condition' => 50
        ]);
        $this->assertEquals(50, $aircraft->total_condition);
    }

    public function test_aircraft_condition_returns_less_than_50(): void
    {
        $aircraft = Aircraft::factory()->create([
            'condition' => 50
        ]);
        AircraftEngine::factory()->create([
            'aircraft_id' => $aircraft->id,
            'condition' => 26
        ]);
        $this->assertLessThan(50, $aircraft->total_condition);
    }


}
