<?php

namespace Tests\Feature\Auth;

use App\Models\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Symfony\Component\HttpFoundation\Response;
use Tests\TestCase;

class LoginTest extends TestCase
{
    use RefreshDatabase;
    protected Model $user;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = User::factory()->create();
    }

    /**
     * A basic feature test example.
     */
    public function test_login_page_responds(): void
    {
        $response = $this->get('/login');
        $response->assertStatus(Response::HTTP_OK);
    }

    public function test_login_successfully(): void
    {
        $data = ['email' => $this->user->email, 'password' => 'password'];
        $this->followingRedirects()->post('/login', $data)
            ->assertStatus(Response::HTTP_OK);

    }

    public function test_login_fails_with_incorrect_credentials(): void
    {
        $data = ['email' => $this->user->email, 'password' => 'notpassword'];
        $this->post('/login', $data)
            ->assertSessionHas('error', 'Invalid credentials.');
    }
}
