<?php

namespace Tests\Feature\Aircraft;

use App\Models\Aircraft;
use App\Models\AircraftEngine;
use App\Models\AircraftManufacturer;
use App\Models\AircraftType;
use App\Models\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class GetFleetTest extends TestCase
{
    use RefreshDatabase;
    protected Model $acType;
    protected Model $manufacturer;
    protected Model $engine;
    protected Model $aircraft;
    protected Model $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->manufacturer = AircraftManufacturer::factory()->create();
        $this->acType = AircraftType::factory()->create([
            'aircraft_manufacturer_id' => $this->manufacturer->id
        ]);
        $this->aircraft = Aircraft::factory()->create([
            'aircraft_type_id' => $this->acType->id
        ]);
        $this->engine = AircraftEngine::factory()->create([
            'aircraft_id' => $this->aircraft->id
        ]);
        $this->user = User::factory()->create();
    }
    /**
     * A basic feature test example.
     */
    public function test_responds_successfully(): void
    {
        $response = $this->actingAs($this->user)->get('/fleet-aircraft');
        $response->assertStatus(200);
    }

    public function test_returns_types(): void
    {
        $response = $this->actingAs($this->user)->get('/fleet-aircraft');
        $response->assertSee(['aircraftTypes']);
    }

    public function test_returns_correct_type(): void
    {
        $response = $this->actingAs($this->user)->get('/fleet-aircraft');
        $response->assertSee(['identifier' => 'C208']);
    }
}
