<?php

namespace Tests\Feature\Contracts;

use App\Models\Contract;
use App\Models\User;
use App\Services\Contracts\AcceptContract;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class AcceptContractTest extends TestCase
{
    use RefreshDatabase;

    protected Model $user;
    protected Model $contract;
    protected AcceptContract $acceptContract;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = User::factory()->create();
        $this->contract = Contract::factory()->create();
    }

    public function test_accept_contract(): void
    {
        $data = [
            'contract_id' => $this->contract->id,
            'user_id' => $this->user->id,
            'is_acceptance' => true
        ];
        $response = $this->followingRedirects()->postJson('/api/contracts/accept', $data);
        $response->assertStatus(200);
        $response->assertSee('Contract successfully accepted');
    }

    public function test_unaccepted_contract(): void
    {
        $data = [
            'contract_id' => $this->contract->id,
            'user_id' => $this->user->id,
            'is_acceptance' => false
        ];
        $response = $this->followingRedirects()->postJson('/api/contracts/accept', $data);
        $response->assertStatus(200);
        $response->assertSee('Contract successfully removed');
    }
}
