<?php

namespace Tests\Unit\Services\Crew;

use App\Models\User;
use App\Services\Crew\UpdateUserLocation;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class UpdateUserLocationTest extends TestCase
{
    use RefreshDatabase;
    protected UpdateUserLocation $updateUserLocation;
    protected Model $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->updateUserLocation = app()->make(UpdateUserLocation::class);
        $this->user = User::factory()->create();
    }

    /**
     * A basic unit test example.
     */
    public function test_user_location_updated(): void
    {
        $this->updateUserLocation->execute($this->user->id, 'AYMN');
        $this->user->refresh();
        $this->assertEquals('AYMN', $this->user->current_airport_id);
    }
}
